import "./globals.css";
import { Roboto } from "next/font/google";

// Components
import Navbar from "./components/full-header-area/header-navbar/Navbar";
import Footer from "./components/Footer/Footer";

const roboto = Roboto({ weight: ["400", "700"], subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className} style={{ backgroundColor: "#001C30" }}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
