import "./globals.css";
import { Roboto } from "next/font/google";
// React toastify
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
// Components
import Navbar from "./components/full-header-area/navbar";
import Footer from "./components/Footer";
import EasypeasyProvider from "./lib/EasypeasyProvider";

const roboto = Roboto({ weight: ["400", "700"], subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className} style={{ backgroundColor: "#001C30" }}>
        <EasypeasyProvider>
          <Navbar />
          {children}
          <Footer />
          <ToastContainer />
        </EasypeasyProvider>
      </body>
    </html>
  );
}
